/*
 * This file is generated by jOOQ.
 */
package com.example.db.tables;


import com.example.db.Keys;
import com.example.db.Public;
import com.example.db.tables.Author.AuthorPath;
import com.example.db.tables.Book.BookPath;
import com.example.db.tables.records.AuthorBookRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthorBook extends TableImpl<AuthorBookRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.author_book</code>
     */
    public static final AuthorBook AUTHOR_BOOK = new AuthorBook();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorBookRecord> getRecordType() {
        return AuthorBookRecord.class;
    }

    /**
     * The column <code>public.author_book.book_id</code>.
     */
    public final TableField<AuthorBookRecord, Integer> BOOK_ID = createField(DSL.name("book_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.author_book.author_id</code>.
     */
    public final TableField<AuthorBookRecord, Integer> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.author_book.created_date_time</code>.
     */
    public final TableField<AuthorBookRecord, LocalDateTime> CREATED_DATE_TIME = createField(DSL.name("created_date_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.author_book.updated_date_time</code>.
     */
    public final TableField<AuthorBookRecord, LocalDateTime> UPDATED_DATE_TIME = createField(DSL.name("updated_date_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private AuthorBook(Name alias, Table<AuthorBookRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuthorBook(Name alias, Table<AuthorBookRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.author_book</code> table reference
     */
    public AuthorBook(String alias) {
        this(DSL.name(alias), AUTHOR_BOOK);
    }

    /**
     * Create an aliased <code>public.author_book</code> table reference
     */
    public AuthorBook(Name alias) {
        this(alias, AUTHOR_BOOK);
    }

    /**
     * Create a <code>public.author_book</code> table reference
     */
    public AuthorBook() {
        this(DSL.name("author_book"), null);
    }

    public <O extends Record> AuthorBook(Table<O> path, ForeignKey<O, AuthorBookRecord> childPath, InverseForeignKey<O, AuthorBookRecord> parentPath) {
        super(path, childPath, parentPath, AUTHOR_BOOK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuthorBookPath extends AuthorBook implements Path<AuthorBookRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuthorBookPath(Table<O> path, ForeignKey<O, AuthorBookRecord> childPath, InverseForeignKey<O, AuthorBookRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuthorBookPath(Name alias, Table<AuthorBookRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuthorBookPath as(String alias) {
            return new AuthorBookPath(DSL.name(alias), this);
        }

        @Override
        public AuthorBookPath as(Name alias) {
            return new AuthorBookPath(alias, this);
        }

        @Override
        public AuthorBookPath as(Table<?> alias) {
            return new AuthorBookPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AuthorBookRecord> getPrimaryKey() {
        return Keys.AUTHOR_BOOK_PKEY;
    }

    @Override
    public List<ForeignKey<AuthorBookRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AUTHOR_BOOK__FK_AUTHOR_BOOK_AUTHOR, Keys.AUTHOR_BOOK__FK_AUTHOR_BOOK_BOOK);
    }

    private transient AuthorPath _author;

    /**
     * Get the implicit join path to the <code>public.author</code> table.
     */
    public AuthorPath author() {
        if (_author == null)
            _author = new AuthorPath(this, Keys.AUTHOR_BOOK__FK_AUTHOR_BOOK_AUTHOR, null);

        return _author;
    }

    private transient BookPath _book;

    /**
     * Get the implicit join path to the <code>public.book</code> table.
     */
    public BookPath book() {
        if (_book == null)
            _book = new BookPath(this, Keys.AUTHOR_BOOK__FK_AUTHOR_BOOK_BOOK, null);

        return _book;
    }

    @Override
    public AuthorBook as(String alias) {
        return new AuthorBook(DSL.name(alias), this);
    }

    @Override
    public AuthorBook as(Name alias) {
        return new AuthorBook(alias, this);
    }

    @Override
    public AuthorBook as(Table<?> alias) {
        return new AuthorBook(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorBook rename(String name) {
        return new AuthorBook(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorBook rename(Name name) {
        return new AuthorBook(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorBook rename(Table<?> name) {
        return new AuthorBook(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBook where(Condition condition) {
        return new AuthorBook(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBook where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBook where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBook where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorBook where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorBook where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorBook where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorBook where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBook whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBook whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
