/*
 * This file is generated by jOOQ.
 */
package com.example.db.tables.records;


import com.example.db.tables.Author;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthorRecord extends UpdatableRecordImpl<AuthorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.author.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.author.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.author.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.author.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.author.birth_date</code>.
     */
    public void setBirthDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.author.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.author.created_date_time</code>.
     */
    public void setCreatedDateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.author.created_date_time</code>.
     */
    public LocalDateTime getCreatedDateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.author.updated_date_time</code>.
     */
    public void setUpdatedDateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.author.updated_date_time</code>.
     */
    public LocalDateTime getUpdatedDateTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorRecord
     */
    public AuthorRecord() {
        super(Author.AUTHOR);
    }

    /**
     * Create a detached, initialised AuthorRecord
     */
    public AuthorRecord(Integer id, String name, LocalDate birthDate, LocalDateTime createdDateTime, LocalDateTime updatedDateTime) {
        super(Author.AUTHOR);

        setId(id);
        setName(name);
        setBirthDate(birthDate);
        setCreatedDateTime(createdDateTime);
        setUpdatedDateTime(updatedDateTime);
        resetChangedOnNotNull();
    }
}
