/*
 * This file is generated by jOOQ.
 */
package com.example.db.tables.records;


import com.example.db.tables.Book;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.book.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.book.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.book.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.book.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.book.price</code>.
     */
    public void setPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.book.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.book.is_published</code>.
     */
    public void setIsPublished(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.book.is_published</code>.
     */
    public Boolean getIsPublished() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.book.created_date_time</code>.
     */
    public void setCreatedDateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.book.created_date_time</code>.
     */
    public LocalDateTime getCreatedDateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.book.updated_date_time</code>.
     */
    public void setUpdatedDateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.book.updated_date_time</code>.
     */
    public LocalDateTime getUpdatedDateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Integer id, String title, Integer price, Boolean isPublished, LocalDateTime createdDateTime, LocalDateTime updatedDateTime) {
        super(Book.BOOK);

        setId(id);
        setTitle(title);
        setPrice(price);
        setIsPublished(isPublished);
        setCreatedDateTime(createdDateTime);
        setUpdatedDateTime(updatedDateTime);
        resetChangedOnNotNull();
    }
}
